/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\BaharRoom.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/BaharRoom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.161, 0.01, 1.774]} rotation={[-Math.PI / 2, 0, 0]} scale={0.342}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 845.383, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={850}>
            <mesh geometry={nodes.ModernBedroom_BedFrame_0.geometry} material={materials.BedFrame} />
            <mesh geometry={nodes.ModernBedroom_Carpet_0.geometry} material={materials.Carpet} />
            <mesh geometry={nodes.ModernBedroom_Duvet_0.geometry} material={materials.Duvet} />
            <mesh geometry={nodes.ModernBedroom_Meshes_0.geometry} material={materials.Meshes} />
            <mesh geometry={nodes.ModernBedroom_Pillows_0.geometry} material={materials.Pillows} />
            <mesh geometry={nodes.ModernBedroom_Structure_0.geometry} material={materials.Structure} />
          </group>
        </group>
      </group>
      <group position={[-3.771, 0.712, 1.985]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.437}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.493, 0.114, -0.938]} scale={[-0.132, -0.225, -0.09]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.038']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.041']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1.937, 0.534, -1.397]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.499, 0.543, 0.499]}>
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.055']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.060']} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.062']} />
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.063']} />
          </group>
          <group position={[0.244, 0.173, -1.164]} rotation={[0.077, -Math.PI / 2, 0]} scale={[0.029, 0.028, 0.042]}>
            <mesh geometry={nodes.Object_83.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.Object_84.geometry} material={materials['Material.032']} />
          </group>
          <group position={[-1.63, 0.1, -0.939]} rotation={[1.571, 0, 0.018]} scale={[0.015, 0.164, 0.015]}>
            <mesh geometry={nodes.Object_109.geometry} material={materials['Material.044']} />
            <mesh geometry={nodes.Object_110.geometry} material={materials['Material.051']} />
          </group>
          <group position={[1.301, 0.251, -1.582]} rotation={[0.371, -1.379, 0.117]} scale={[0.015, 0.164, 0.015]}>
            <mesh geometry={nodes.Object_63.geometry} material={materials['Material.043']} />
            <mesh geometry={nodes.Object_64.geometry} material={materials['Material.044']} />
            <mesh geometry={nodes.Object_65.geometry} material={materials['Material.051']} />
          </group>
          <group position={[1.361, 0.251, -1.611]} rotation={[0.083, -0.582, -0.202]} scale={[0.015, 0.164, 0.015]}>
            <mesh geometry={nodes.Object_67.geometry} material={materials['Material.045']} />
            <mesh geometry={nodes.Object_68.geometry} material={materials['Material.046']} />
            <mesh geometry={nodes.Object_69.geometry} material={materials['Material.047']} />
          </group>
          <group position={[-1.265, 0.132, -1.154]} rotation={[0, -1.571, 0]} scale={[0.008, 0.002, 0.008]}>
            <mesh geometry={nodes.Object_94.geometry} material={materials['Material.029']} position={[0.001, 0, 0]} />
          </group>
          <group position={[1.542, 0.116, -1.201]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.005, 0.001, 0.005]}>
            <mesh geometry={nodes.Object_98.geometry} material={materials['Material.001']} position={[0, 0.003, 0]} />
          </group>
          <group position={[1.58, 0.116, -1.201]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.002, 0.001, 0.002]}>
            <mesh geometry={nodes.Object_100.geometry} material={materials['Material.001']} position={[0, 0.004, 0]} />
          </group>
          <group position={[0.185, 1.423, -1.918]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.01, 0.002, 0.01]}>
            <mesh geometry={nodes.Object_104.geometry} material={materials['Material.034']} position={[0, 0.003, 0]} />
          </group>
          <group position={[-1.459, 0.729, -1.97]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.005, 0.001, 0.005]}>
            <mesh geometry={nodes.Object_116.geometry} material={materials['Material.034']} position={[0, 0.002, 0]} />
          </group>
          <group position={[2.085, 0.708, -1.846]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.126, 0.056, 0.126]}>
            <mesh geometry={nodes.Object_122.geometry} material={materials['Material.059']} />
            <mesh geometry={nodes.Object_123.geometry} material={materials['Material.442']} />
          </group>
          <group position={[2.085, 0.398, -1.846]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.126, 0.056, 0.126]}>
            <mesh geometry={nodes.Object_127.geometry} material={materials['Material.059']} />
            <mesh geometry={nodes.Object_128.geometry} material={materials['Material.442']} />
          </group>
          <mesh geometry={nodes.Object_49.geometry} material={materials['Material.036']} position={[-0.797, 0.372, -1.829]} rotation={[-Math.PI, 0.583, -Math.PI]} scale={[0.058, 0.066, 0.033]} />
          <mesh geometry={nodes.Object_51.geometry} material={materials['Material.036']} position={[-0.718, 0.377, -1.872]} rotation={[3.003, 0, Math.PI]} scale={[0.049, 0.056, 0.028]} />
          <mesh geometry={nodes.Object_53.geometry} material={materials['Material.036']} position={[-0.784, 0.38, -1.872]} rotation={[Math.PI, -1.232, 3.054]} scale={[0.058, 0.066, 0.033]} />
          <mesh geometry={nodes.Object_55.geometry} material={materials['Material.036']} position={[-0.723, 0.405, -1.824]} rotation={[Math.PI, 0, Math.PI]} scale={[0.058, 0.066, 0.033]} />
          <mesh geometry={nodes.Object_57.geometry} material={materials['Material.036']} position={[-0.849, 0.402, -1.836]} rotation={[Math.PI, 1.005, 2.969]} scale={[0.058, 0.066, 0.033]} />
          <mesh geometry={nodes.Object_59.geometry} material={materials['Material.036']} position={[-0.78, 0.37, -1.738]} rotation={[-2.996, 0, -Math.PI]} scale={[0.081, 0.066, 0.033]} />
          <mesh geometry={nodes.Object_61.geometry} material={materials['Material.036']} position={[-0.66, 0.364, -1.833]} rotation={[2.428, 1.326, -2.543]} scale={[0.081, 0.066, 0.033]} />
          <mesh geometry={nodes.Object_47.geometry} material={materials['Material.036']} position={[-0.708, 0.346, -1.767]} rotation={[-3.002, 0, -Math.PI]} scale={[0.058, 0.066, 0.033]} />
          <mesh geometry={nodes.Object_45.geometry} material={materials['Material.052']} position={[-1.616, -0.798, -1.237]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.379, 0.381, 0.319]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.052']} position={[2.14, -0.798, -1.237]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.379, 0.381, 0.319]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.030']} position={[0.239, 0.032, -1.16]} rotation={[0, 1.571, 0]} scale={[-0.392, -0.007, -0.474]} />
          <mesh geometry={nodes.Object_21.geometry} material={materials['Material.038']} position={[0.232, 0.151, -1.166]} rotation={[0, 1.571, 0]} scale={[-0.218, -0.606, -0.136]} />
          <mesh geometry={nodes.Object_19.geometry} material={materials['Material.019']} position={[0.468, 0.88, -1.993]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.499, 0.543, 0.471]} />
          <mesh geometry={nodes.Object_23.geometry} material={materials['Material.019']} position={[0.212, 0.114, -1.855]} scale={[-0.168, -0.322, -0.104]} />
          <mesh geometry={nodes.Object_25.geometry} material={materials['Material.019']} position={[0.212, 0.114, -1.855]} scale={[-0.305, -0.322, -0.104]} />
          <mesh geometry={nodes.Object_27.geometry} material={materials['Material.024']} position={[-1.547, 0.112, -1.769]} rotation={[0, 1.571, 0]} scale={[-0.209, -0.312, -0.127]} />
          <mesh geometry={nodes.Object_29.geometry} material={materials['Material.019']} position={[-1.547, 0.396, -1.995]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-0.196, -0.377, -0.127]} />
          <mesh geometry={nodes.Object_71.geometry} material={materials['Material.019']} position={[0.216, 1.418, -1.967]} rotation={[0, -1.571, 0]} scale={[0.049, 0.102, 0.233]} />
          <mesh geometry={nodes.Object_73.geometry} material={materials['Material.019']} position={[0.216, 1.286, -1.981]} rotation={[Math.PI, 0, Math.PI]} scale={[0.049, 0.041, 0.095]} />
          <mesh geometry={nodes.monitor.geometry} material={materials['Material.042']} position={[0.468, 0.88, -1.993]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.499, 0.543, 0.471]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials['Material.022']} position={[-1.547, 0.396, -1.995]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-0.196, -0.377, -0.127]} />
          <mesh geometry={nodes.Object_106.geometry} material={materials['Material.048']} position={[0.232, 0.151, -1.166]} rotation={[0, 1.571, 0]} scale={[-0.218, -0.606, -0.136]} />
          <mesh geometry={nodes.Object_79.geometry} material={materials['Material.035']} position={[0.012, 0.161, -1.012]} rotation={[0.077, -Math.PI / 2, 0]} scale={[0.029, 0.028, 0.044]} />
          <mesh geometry={nodes.Object_81.geometry} material={materials['Material.031']} position={[0.207, 0.161, -1.012]} rotation={[0.077, -Math.PI / 2, 0]} scale={[0.029, 0.028, 0.133]} />
          <mesh geometry={nodes.Object_88.geometry} material={materials['Material.025']} position={[-1.47, 0.13, -1.762]} rotation={[-0.007, -Math.PI / 2, 0]} scale={[0.027, 0.011, 0.042]} />
          <mesh geometry={nodes.Object_90.geometry} material={materials['Material.023']} position={[-1.506, 0.123, -1.492]} rotation={[0, -1.571, 0]} scale={[0.073, 0.004, 0.132]} />
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.026']} position={[-0.985, 0, -1.397]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_41.geometry} material={materials['Material.037']} position={[-0.76, 0.201, -1.818]} rotation={[Math.PI, -0.968, Math.PI]} scale={[0.108, 0.119, 0.108]} />
          <mesh geometry={nodes.Object_43.geometry} material={materials['Material.037']} position={[1.312, 0.194, -1.635]} rotation={[Math.PI, -0.968, Math.PI]} scale={0.108} />
          <mesh geometry={nodes.Object_114.geometry} material={materials['Material.047']} position={[-1.496, 0.099, -0.98]} rotation={[3.057, 1.363, -1.488]} scale={[0.015, 0.164, 0.015]} />
          <mesh geometry={nodes.Object_75.geometry} material={materials['Material.027']} position={[-1.265, 0.128, -1.154]} rotation={[0, -1.571, 0]} scale={[0.019, 0.004, 0.019]} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.material_0} position={[-1.22, 0.128, -1.154]} rotation={[0, -1.571, 0]} scale={[0.009, 0.002, 0.009]} />
          <mesh geometry={nodes.Object_96.geometry} material={materials['Material.001']} position={[1.493, 0.132, -1.175]} rotation={[0, -1.571, 0]} scale={[0.01, 0.002, 0.01]} />
          <mesh geometry={nodes.Object_102.geometry} material={materials['Material.027']} position={[0.124, 1.424, -1.918]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.025, 0.006, 0.025]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials['Material.027']} position={[1.962, 0.803, -0.895]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.025, 0.006, 0.025]} />
          <mesh geometry={nodes.Object_120.geometry} material={materials['Material.027']} position={[1.962, 0.734, -0.895]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.016, 0.004, 0.016]} />
          <mesh geometry={nodes.Object_125.geometry} material={materials['Material.058']} position={[2.085, 0.708, -1.846]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.126, 0.056, 0.126]} />
          <mesh geometry={nodes.Object_130.geometry} material={materials['Material.061']} position={[2.085, 0.398, -1.846]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.126, 0.056, 0.126]} />
          <mesh geometry={nodes.Object_132.geometry} material={materials['Material.068']} position={[1.493, 0.133, -1.175]} rotation={[0, -1.571, 0]} scale={[0.005, 0.001, 0.005]} />
          <mesh geometry={nodes.Object_33.geometry} material={materials['Material.053']} position={[1.925, 0.19, -0.685]} rotation={[Math.PI, -0.968, Math.PI]} scale={0.108} />
          <mesh geometry={nodes.Object_37.geometry} material={materials['Material.039']} position={[0.935, 0.088, -1.127]} rotation={[0, -1.571, 0]} scale={[0.17, 0.09, 0.112]} />
          <mesh geometry={nodes.Object_39.geometry} material={materials['Material.040']} position={[0.93, 0.164, -1.179]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.066, 0.057, 0.057]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials['Material.053']} position={[2.014, 0.188, -0.639]} rotation={[Math.PI, -0.968, Math.PI / 2]} scale={0.056} />
        </group>
      </group>
      <group position={[2.298, 0.018, 3.34]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={1.763}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Frame_Metal_0002.geometry} material={materials['Metal.002']} />
          <mesh geometry={nodes.Plane1_Planes_0002.geometry} material={materials['Planes.002']} />
          <mesh geometry={nodes.Plane2_Planes_0002.geometry} material={materials['Planes.002']} />
          <mesh geometry={nodes.Plane3_Planes_0002.geometry} material={materials['Planes.002']} />
          <mesh geometry={nodes.Plane4_Planes_0002.geometry} material={materials['Planes.002']} />
          <mesh geometry={nodes.Plane5_Planes_0002.geometry} material={materials['Planes.002']} />
        </group>
      </group>
      <group position={[2.165, 0.01, 1.774]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.004, 0, -0.006]} scale={1.849}>
            <group position={[0.009, 0.062, 0.136]} rotation={[-Math.PI / 2, 0, 0.044]} scale={-0.01}>
              <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
              <mesh geometry={nodes.Object_6002.geometry} material={materials.material_1} />
            </group>
            <group position={[-0.03, 0.673, -0.069]} rotation={[-1.763, 0.045, -1.897]} scale={-0.024}>
              <mesh geometry={nodes.Object_10002.geometry} material={materials.material_4} />
              <mesh geometry={nodes.Object_8001.geometry} material={materials.material_2} />
              <mesh geometry={nodes.Object_9.geometry} material={materials.material_3} />
            </group>
          </group>
        </group>
      </group>
      <group position={[2.432, 0.01, -0.806]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.202}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.353, 6.114, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.128}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.book003} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.book003} position={[35.154, 0, -15.951]} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.book003} position={[5.498, 0, -31.669]} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.book003} position={[35.154, 0, -48.162]} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.book003} position={[-11.15, 0, -16.028]} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.book003} position={[47.93, 0, -0.31]} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.book003} position={[52.204, 0, -15.827]} />
            <mesh geometry={nodes.Object_34.geometry} material={materials.book003} position={[23.771, 0, -31.716]} />
            <mesh geometry={nodes.Object_36.geometry} material={materials.book003} position={[47.93, 0, -31.623]} />
            <mesh geometry={nodes.Object_38.geometry} material={materials.book003} position={[18.271, 0, -48.237]} />
            <mesh geometry={nodes.Object_40.geometry} material={materials.book003} position={[51.944, 0, -48.125]} />
            <mesh geometry={nodes.Object_42.geometry} material={materials.book003} position={[-5.591, 0, -48.014]} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.book003} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_46.geometry} material={materials.book002} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_48.geometry} material={materials.book002} position={[35.154, 0, -15.951]} />
            <mesh geometry={nodes.Object_50.geometry} material={materials.book002} position={[5.498, 0, -31.669]} />
            <mesh geometry={nodes.Object_52.geometry} material={materials.book002} position={[35.154, 0, -48.162]} />
            <mesh geometry={nodes.Object_54.geometry} material={materials.book002} position={[-11.15, 0, -16.028]} />
            <mesh geometry={nodes.Object_56.geometry} material={materials.book002} position={[47.93, 0, -0.31]} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.book002} position={[52.204, 0, -15.827]} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.book002} position={[23.771, 0, -31.716]} />
            <mesh geometry={nodes.Object_62.geometry} material={materials.book002} position={[47.93, 0, -31.623]} />
            <mesh geometry={nodes.Object_64001.geometry} material={materials.book002} position={[18.271, 0, -48.237]} />
            <mesh geometry={nodes.Object_66.geometry} material={materials.book002} position={[51.944, 0, -48.125]} />
            <mesh geometry={nodes.Object_68001.geometry} material={materials.book002} position={[-5.591, 0, -48.014]} />
            <mesh geometry={nodes.Object_44.geometry} material={materials.book002} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_72.geometry} material={materials.book004} position={[-11.15, 0, -16.028]} />
            <mesh geometry={nodes.Object_74.geometry} material={materials.book004} position={[47.93, 0, -0.31]} />
            <mesh geometry={nodes.Object_76.geometry} material={materials.book004} position={[52.204, 0, -15.827]} />
            <mesh geometry={nodes.Object_78.geometry} material={materials.book004} position={[23.771, 0, -31.716]} />
            <mesh geometry={nodes.Object_80.geometry} material={materials.book004} position={[47.93, 0, -31.623]} />
            <mesh geometry={nodes.Object_82.geometry} material={materials.book004} position={[18.271, 0, -48.237]} />
            <mesh geometry={nodes.Object_84001.geometry} material={materials.book004} position={[51.944, 0, -48.125]} />
            <mesh geometry={nodes.Object_86001.geometry} material={materials.book004} position={[-5.591, 0, -48.014]} />
            <mesh geometry={nodes.Object_70.geometry} material={materials.book004} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_90001.geometry} material={materials.book005} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_92001.geometry} material={materials.book005} position={[35.154, 0, -15.951]} />
            <mesh geometry={nodes.Object_94001.geometry} material={materials.book005} position={[5.498, 0, -31.669]} />
            <mesh geometry={nodes.Object_96001.geometry} material={materials.book005} position={[35.154, 0, -48.162]} />
            <mesh geometry={nodes.Object_98001.geometry} material={materials.book005} position={[-11.15, 0, -16.028]} />
            <mesh geometry={nodes.Object_100001.geometry} material={materials.book005} position={[47.93, 0, -0.31]} />
            <mesh geometry={nodes.Object_102001.geometry} material={materials.book005} position={[52.204, 0, -15.827]} />
            <mesh geometry={nodes.Object_104001.geometry} material={materials.book005} position={[23.771, 0, -31.716]} />
            <mesh geometry={nodes.Object_106001.geometry} material={materials.book005} position={[47.93, 0, -31.623]} />
            <mesh geometry={nodes.Object_108.geometry} material={materials.book005} position={[18.271, 0, -48.237]} />
            <mesh geometry={nodes.Object_110001.geometry} material={materials.book005} position={[51.944, 0, -48.125]} />
            <mesh geometry={nodes.Object_112.geometry} material={materials.book005} position={[-5.591, 0, -48.014]} />
            <mesh geometry={nodes.Object_88001.geometry} material={materials.book005} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_116001.geometry} material={materials.book006} position={[-11.15, 0, -16.028]} />
            <mesh geometry={nodes.Object_118001.geometry} material={materials.book006} position={[47.93, 0, -0.31]} />
            <mesh geometry={nodes.Object_120001.geometry} material={materials.book006} position={[52.204, 0, -15.827]} />
            <mesh geometry={nodes.Object_122001.geometry} material={materials.book006} position={[23.771, 0, -31.716]} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.book006} position={[47.93, 0, -31.623]} />
            <mesh geometry={nodes.Object_126.geometry} material={materials.book006} position={[18.271, 0, -48.237]} />
            <mesh geometry={nodes.Object_128001.geometry} material={materials.book006} position={[51.944, 0, -48.125]} />
            <mesh geometry={nodes.Object_130001.geometry} material={materials.book006} position={[-5.591, 0, -48.014]} />
            <mesh geometry={nodes.Object_114001.geometry} material={materials.book006} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_134.geometry} material={materials.book01} position={[35.154, 0, -15.951]} />
            <mesh geometry={nodes.Object_136.geometry} material={materials.book01} position={[5.498, 0, -31.669]} />
            <mesh geometry={nodes.Object_138.geometry} material={materials.book01} position={[35.154, 0, -48.162]} />
            <mesh geometry={nodes.Object_140.geometry} material={materials.book01} position={[-11.15, 0, -16.028]} />
            <mesh geometry={nodes.Object_142.geometry} material={materials.book01} position={[47.93, 0, -0.31]} />
            <mesh geometry={nodes.Object_144.geometry} material={materials.book01} position={[52.204, 0, -15.827]} />
            <mesh geometry={nodes.Object_146.geometry} material={materials.book01} position={[23.771, 0, -31.716]} />
            <mesh geometry={nodes.Object_148.geometry} material={materials.book01} position={[47.93, 0, -31.623]} />
            <mesh geometry={nodes.Object_150.geometry} material={materials.book01} position={[18.271, 0, -48.237]} />
            <mesh geometry={nodes.Object_152.geometry} material={materials.book01} position={[51.944, 0, -48.125]} />
            <mesh geometry={nodes.Object_154.geometry} material={materials.book01} position={[-5.591, 0, -48.014]} />
            <mesh geometry={nodes.Object_132001.geometry} material={materials.book01} position={[0, 0, -0.31]} />
            <mesh geometry={nodes.Object_158.geometry} material={materials.magaz1} position={[-11.15, 0, -16.028]} />
            <mesh geometry={nodes.Object_160.geometry} material={materials.magaz1} position={[47.93, 0, -0.31]} />
            <mesh geometry={nodes.Object_162.geometry} material={materials.magaz1} position={[52.204, 0, -15.827]} />
            <mesh geometry={nodes.Object_164.geometry} material={materials.magaz1} position={[23.771, 0, -31.716]} />
            <mesh geometry={nodes.Object_166.geometry} material={materials.magaz1} position={[47.93, 0, -31.623]} />
            <mesh geometry={nodes.Object_168.geometry} material={materials.magaz1} position={[18.271, 0, -48.237]} />
            <mesh geometry={nodes.Object_170.geometry} material={materials.magaz1} position={[51.944, 0, -48.125]} />
            <mesh geometry={nodes.Object_172.geometry} material={materials.magaz1} position={[-5.591, 0, -48.014]} />
            <mesh geometry={nodes.Object_156.geometry} material={materials.magaz1} position={[0, 0, -0.31]} />
          </group>
          <group position={[3.438, 6.079, 0]} rotation={[-Math.PI / 2, 0, 0.046]} scale={0.514}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Object_658.geometry} material={materials['Material.088']} />
              <mesh geometry={nodes.Object_660.geometry} material={materials['Material.089']} />
              <mesh geometry={nodes.Object_662.geometry} material={materials['Material.090']} />
              <mesh geometry={nodes.Object_664.geometry} material={materials['Material.091']} />
              <mesh geometry={nodes.Object_666.geometry} material={materials['Material.092']} />
            </group>
          </group>
          <mesh geometry={nodes.Object_602.geometry} material={materials.BookPaper} position={[0.081, 2.019, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_618.geometry} material={materials.BookPaper} position={[3.098, 4.066, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_634.geometry} material={materials.BookPaper} position={[3.554, 4.066, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_650.geometry} material={materials.BookPaper} position={[9.084, 6.057, 0.42]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.BookPaper} position={[0.777, 4.041, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_604.geometry} material={materials.BookCover10} position={[0.081, 2.019, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_620.geometry} material={materials.BookCover10} position={[3.098, 4.066, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_636.geometry} material={materials.BookCover10} position={[3.554, 4.066, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_652.geometry} material={materials.BookCover10} position={[9.084, 6.057, 0.42]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_212.geometry} material={materials.BookCover10} position={[0.777, 4.041, 0.062]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.BookPaper} position={[2.209, 2.01, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_250.geometry} material={materials.BookPaper} position={[2.199, 4.039, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_266.geometry} material={materials.BookPaper} position={[-0.885, 6.068, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_282.geometry} material={materials.BookPaper} position={[5.044, 6.068, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_298.geometry} material={materials.BookPaper} position={[6.098, 4.069, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_314.geometry} material={materials.BookPaper} position={[8.645, 2, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_330.geometry} material={materials.BookPaper} position={[6.095, -0.092, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_346.geometry} material={materials.BookPaper} position={[2.256, -0.078, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_362.geometry} material={materials.BookPaper} position={[-0.861, -0.078, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_214.geometry} material={materials.BookPaper} position={[-0.845, 2.049, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_236.geometry} material={materials.BookCover11} position={[2.209, 2.01, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_252.geometry} material={materials.BookCover11} position={[2.199, 4.039, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_268.geometry} material={materials.BookCover11} position={[-0.885, 6.068, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_284.geometry} material={materials.BookCover11} position={[5.044, 6.068, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_300.geometry} material={materials.BookCover11} position={[6.098, 4.069, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.BookCover11} position={[8.645, 2, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_332.geometry} material={materials.BookCover11} position={[6.095, -0.092, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_348.geometry} material={materials.BookCover11} position={[2.256, -0.078, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_364.geometry} material={materials.BookCover11} position={[-0.861, -0.078, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.BookCover11} position={[-0.845, 2.049, 0.254]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_378.geometry} material={materials.BookPaper} position={[2.216, 6.064, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_394.geometry} material={materials.BookPaper} position={[6.083, 6.052, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_410.geometry} material={materials.BookPaper} position={[4.412, 4.071, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_426.geometry} material={materials.BookPaper} position={[1.368, 4.047, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_442.geometry} material={materials.BookPaper} position={[5.176, 2.041, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_458.geometry} material={materials.BookPaper} position={[6.095, 2.017, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_474.geometry} material={materials.BookPaper} position={[8.769, 4.059, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_490.geometry} material={materials.BookPaper} position={[0.623, 2.718, -0.26]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_506.geometry} material={materials.BookPaper} position={[3.001, 2.746, -0.26]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_522.geometry} material={materials.BookPaper} position={[8.774, 0.64, -0.26]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_538.geometry} material={materials.BookPaper} position={[4.419, 0.655, -0.26]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_554.geometry} material={materials.BookPaper} position={[1.382, 0.655, -0.26]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_570.geometry} material={materials.BookPaper} position={[4.348, 6.786, -0.26]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_586.geometry} material={materials.BookPaper} position={[4.348, 6.786, -0.26]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_218.geometry} material={materials.BookPaper} position={[-0.124, 6.064, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_380.geometry} material={materials.BookCover12} position={[2.216, 6.064, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_396.geometry} material={materials.BookCover12} position={[6.083, 6.052, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_412.geometry} material={materials.BookCover12} position={[4.412, 4.071, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_428.geometry} material={materials.BookCover12} position={[1.368, 4.047, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_444.geometry} material={materials.BookCover12} position={[5.176, 2.041, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_460.geometry} material={materials.BookCover12} position={[6.095, 2.017, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_476.geometry} material={materials.BookCover12} position={[8.769, 4.059, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_492.geometry} material={materials.BookCover12} position={[0.569, 2.718, 0.187]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_508.geometry} material={materials.BookCover12} position={[2.947, 2.746, 0.187]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_524.geometry} material={materials.BookCover12} position={[8.72, 0.64, 0.187]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_540.geometry} material={materials.BookCover12} position={[4.365, 0.655, 0.187]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_556.geometry} material={materials.BookCover12} position={[1.328, 0.655, 0.187]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_572.geometry} material={materials.BookCover12} position={[4.293, 6.786, 0.187]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_588.geometry} material={materials.BookCover12} position={[4.293, 6.786, 0.187]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_220.geometry} material={materials.BookCover12} position={[-0.124, 6.064, -0.102]} rotation={[-Math.PI / 2, 0, -1.692]} scale={[0.736, 1.073, 0.736]} />
          <mesh geometry={nodes.Object_366.geometry} material={materials.BookPaper} position={[2.384, 6.064, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_382.geometry} material={materials.BookPaper} position={[6.252, 6.052, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_398.geometry} material={materials.BookPaper} position={[4.581, 4.071, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_414.geometry} material={materials.BookPaper} position={[1.537, 4.047, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_430.geometry} material={materials.BookPaper} position={[5.345, 2.041, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_446.geometry} material={materials.BookPaper} position={[6.264, 2.017, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_462.geometry} material={materials.BookPaper} position={[8.938, 4.059, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_478.geometry} material={materials.BookPaper} position={[0.792, 2.718, -0.182]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_494.geometry} material={materials.BookPaper} position={[3.17, 2.746, -0.182]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_510.geometry} material={materials.BookPaper} position={[8.943, 0.64, -0.182]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_526.geometry} material={materials.BookPaper} position={[4.588, 0.655, -0.182]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_542.geometry} material={materials.BookPaper} position={[1.551, 0.655, -0.182]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_558.geometry} material={materials.BookPaper} position={[4.516, 6.786, -0.182]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_574.geometry} material={materials.BookPaper} position={[4.516, 6.786, -0.182]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.BookPaper} position={[0.044, 6.064, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_368.geometry} material={materials.BookCover1} position={[2.384, 6.064, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_384.geometry} material={materials.BookCover1} position={[6.252, 6.052, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_400.geometry} material={materials.BookCover1} position={[4.581, 4.071, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_416.geometry} material={materials.BookCover1} position={[1.537, 4.047, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_432.geometry} material={materials.BookCover1} position={[5.345, 2.041, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_448.geometry} material={materials.BookCover1} position={[6.264, 2.017, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_464.geometry} material={materials.BookCover1} position={[8.938, 4.059, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_480.geometry} material={materials.BookCover1} position={[0.737, 2.718, 0.265]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_496.geometry} material={materials.BookCover1} position={[3.115, 2.746, 0.265]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_512.geometry} material={materials.BookCover1} position={[8.889, 0.64, 0.265]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_528.geometry} material={materials.BookCover1} position={[4.534, 0.655, 0.265]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_544.geometry} material={materials.BookCover1} position={[1.497, 0.655, 0.265]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_560.geometry} material={materials.BookCover1} position={[4.462, 6.786, 0.265]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_576.geometry} material={materials.BookCover1} position={[4.462, 6.786, 0.265]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_176.geometry} material={materials.BookCover1} position={[0.044, 6.064, -0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_370.geometry} material={materials.BookPaper} position={[2.539, 6.064, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_386.geometry} material={materials.BookPaper} position={[6.407, 6.052, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_402.geometry} material={materials.BookPaper} position={[4.735, 4.071, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_418.geometry} material={materials.BookPaper} position={[1.691, 4.047, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_434.geometry} material={materials.BookPaper} position={[5.499, 2.041, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_450.geometry} material={materials.BookPaper} position={[6.419, 2.017, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_466.geometry} material={materials.BookPaper} position={[9.093, 4.059, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_482.geometry} material={materials.BookPaper} position={[0.947, 2.718, -0.242]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_498.geometry} material={materials.BookPaper} position={[3.325, 2.746, -0.242]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_514.geometry} material={materials.BookPaper} position={[9.098, 0.64, -0.242]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_530.geometry} material={materials.BookPaper} position={[4.743, 0.655, -0.242]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_546.geometry} material={materials.BookPaper} position={[1.706, 0.655, -0.242]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_562.geometry} material={materials.BookPaper} position={[4.671, 6.786, -0.242]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_578.geometry} material={materials.BookPaper} position={[4.671, 6.786, -0.242]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.BookPaper} position={[0.199, 6.064, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_372.geometry} material={materials.BookCover2} position={[2.539, 6.064, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_388.geometry} material={materials.BookCover2} position={[6.407, 6.052, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_404.geometry} material={materials.BookCover2} position={[4.735, 4.071, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_420.geometry} material={materials.BookCover2} position={[1.691, 4.047, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_436.geometry} material={materials.BookCover2} position={[5.499, 2.041, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_452.geometry} material={materials.BookCover2} position={[6.419, 2.017, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_468.geometry} material={materials.BookCover2} position={[9.093, 4.059, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_484.geometry} material={materials.BookCover2} position={[0.892, 2.718, 0.206]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_500.geometry} material={materials.BookCover2} position={[3.27, 2.746, 0.206]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_516.geometry} material={materials.BookCover2} position={[9.043, 0.64, 0.206]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_532.geometry} material={materials.BookCover2} position={[4.688, 0.655, 0.206]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_548.geometry} material={materials.BookCover2} position={[1.651, 0.655, 0.206]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_564.geometry} material={materials.BookCover2} position={[4.617, 6.786, 0.206]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_580.geometry} material={materials.BookCover2} position={[4.617, 6.786, 0.206]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.BookCover2} position={[0.199, 6.064, -0.084]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_374.geometry} material={materials.BookPaper} position={[2.657, 6.064, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_390.geometry} material={materials.BookPaper} position={[6.525, 6.052, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_406.geometry} material={materials.BookPaper} position={[4.854, 4.071, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_422.geometry} material={materials.BookPaper} position={[1.81, 4.047, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_438.geometry} material={materials.BookPaper} position={[5.618, 2.041, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_454.geometry} material={materials.BookPaper} position={[6.537, 2.017, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_470.geometry} material={materials.BookPaper} position={[9.211, 4.059, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_486.geometry} material={materials.BookPaper} position={[1.065, 2.799, -0.133]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_502.geometry} material={materials.BookPaper} position={[3.443, 2.828, -0.133]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_518.geometry} material={materials.BookPaper} position={[9.216, 0.722, -0.133]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_534.geometry} material={materials.BookPaper} position={[4.861, 0.736, -0.133]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_550.geometry} material={materials.BookPaper} position={[1.824, 0.736, -0.133]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_566.geometry} material={materials.BookPaper} position={[4.789, 6.868, -0.133]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_582.geometry} material={materials.BookPaper} position={[4.789, 6.868, -0.133]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_182.geometry} material={materials.BookPaper} position={[0.317, 6.064, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_376.geometry} material={materials.BookCover3} position={[2.657, 6.064, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_392.geometry} material={materials.BookCover3} position={[6.525, 6.052, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_408.geometry} material={materials.BookCover3} position={[4.854, 4.071, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_424.geometry} material={materials.BookCover3} position={[1.81, 4.047, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_440.geometry} material={materials.BookCover3} position={[5.618, 2.041, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_456.geometry} material={materials.BookCover3} position={[6.537, 2.017, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_472.geometry} material={materials.BookCover3} position={[9.211, 4.059, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_488.geometry} material={materials.BookCover3} position={[1.01, 2.799, 0.314]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_504.geometry} material={materials.BookCover3} position={[3.388, 2.828, 0.314]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_520.geometry} material={materials.BookCover3} position={[9.161, 0.722, 0.314]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_536.geometry} material={materials.BookCover3} position={[4.807, 0.736, 0.314]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_552.geometry} material={materials.BookCover3} position={[1.77, 0.736, 0.314]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_568.geometry} material={materials.BookCover3} position={[4.735, 6.868, 0.314]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_584.geometry} material={materials.BookCover3} position={[4.735, 6.868, 0.314]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_184.geometry} material={materials.BookCover3} position={[0.317, 6.064, 0.024]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.736} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.BookPaper} position={[2.717, 2.01, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_238.geometry} material={materials.BookPaper} position={[2.708, 4.039, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_254.geometry} material={materials.BookPaper} position={[-0.376, 6.068, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_270.geometry} material={materials.BookPaper} position={[5.553, 6.068, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_286.geometry} material={materials.BookPaper} position={[6.607, 4.069, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_302.geometry} material={materials.BookPaper} position={[9.154, 2, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_318.geometry} material={materials.BookPaper} position={[6.604, -0.092, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_334.geometry} material={materials.BookPaper} position={[2.765, -0.078, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_350.geometry} material={materials.BookPaper} position={[-0.352, -0.078, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.BookPaper} position={[-0.337, 2.049, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_224.geometry} material={materials.BookCover4} position={[2.717, 2.01, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_240.geometry} material={materials.BookCover4} position={[2.708, 4.039, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_256.geometry} material={materials.BookCover4} position={[-0.376, 6.068, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_272.geometry} material={materials.BookCover4} position={[5.553, 6.068, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_288.geometry} material={materials.BookCover4} position={[6.607, 4.069, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_304.geometry} material={materials.BookCover4} position={[9.154, 2, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_320.geometry} material={materials.BookCover4} position={[6.604, -0.092, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_336.geometry} material={materials.BookCover4} position={[2.765, -0.078, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_352.geometry} material={materials.BookCover4} position={[-0.352, -0.078, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_188.geometry} material={materials.BookCover4} position={[-0.337, 2.049, 0.273]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_226.geometry} material={materials.BookPaper} position={[2.559, 2.01, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_242.geometry} material={materials.BookPaper} position={[2.549, 4.039, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.BookPaper} position={[-0.535, 6.068, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.BookPaper} position={[5.394, 6.068, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_290.geometry} material={materials.BookPaper} position={[6.449, 4.069, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_306.geometry} material={materials.BookPaper} position={[8.996, 2, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_322.geometry} material={materials.BookPaper} position={[6.446, -0.092, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_338.geometry} material={materials.BookPaper} position={[2.607, -0.078, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_354.geometry} material={materials.BookPaper} position={[-0.511, -0.078, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.BookPaper} position={[-0.495, 2.049, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.BookCover5} position={[2.559, 2.01, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_244.geometry} material={materials.BookCover5} position={[2.549, 4.039, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_260.geometry} material={materials.BookCover5} position={[-0.535, 6.068, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_276.geometry} material={materials.BookCover5} position={[5.394, 6.068, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_292.geometry} material={materials.BookCover5} position={[6.449, 4.069, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_308.geometry} material={materials.BookCover5} position={[8.996, 2, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_324.geometry} material={materials.BookCover5} position={[6.446, -0.092, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_340.geometry} material={materials.BookCover5} position={[2.607, -0.078, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_356.geometry} material={materials.BookCover5} position={[-0.511, -0.078, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.BookCover5} position={[-0.495, 2.049, 0.244]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_230.geometry} material={materials.BookPaper} position={[2.392, 2.01, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_246.geometry} material={materials.BookPaper} position={[2.382, 4.039, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.BookPaper} position={[-0.702, 6.068, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_278.geometry} material={materials.BookPaper} position={[5.227, 6.068, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_294.geometry} material={materials.BookPaper} position={[6.282, 4.069, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_310.geometry} material={materials.BookPaper} position={[8.828, 2, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_326.geometry} material={materials.BookPaper} position={[6.279, -0.092, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_342.geometry} material={materials.BookPaper} position={[2.439, -0.078, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_358.geometry} material={materials.BookPaper} position={[-0.678, -0.078, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_194.geometry} material={materials.BookPaper} position={[-0.662, 2.049, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_232.geometry} material={materials.BookCover6} position={[2.392, 2.01, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_248.geometry} material={materials.BookCover6} position={[2.382, 4.039, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.BookCover6} position={[-0.702, 6.068, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_280.geometry} material={materials.BookCover6} position={[5.227, 6.068, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_296.geometry} material={materials.BookCover6} position={[6.282, 4.069, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_312.geometry} material={materials.BookCover6} position={[8.828, 2, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_328.geometry} material={materials.BookCover6} position={[6.279, -0.092, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_344.geometry} material={materials.BookCover6} position={[2.439, -0.078, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_360.geometry} material={materials.BookCover6} position={[-0.678, -0.078, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_196.geometry} material={materials.BookCover6} position={[-0.662, 2.049, 0.247]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.819} />
          <mesh geometry={nodes.Object_590.geometry} material={materials.BookPaper} position={[-0.117, 2.019, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_606.geometry} material={materials.BookPaper} position={[2.9, 4.066, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_622.geometry} material={materials.BookPaper} position={[3.356, 4.066, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_638.geometry} material={materials.BookPaper} position={[8.886, 6.057, 0.348]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.BookPaper} position={[0.579, 4.041, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_592.geometry} material={materials.BookCover7} position={[-0.117, 2.019, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_608.geometry} material={materials.BookCover7} position={[2.9, 4.066, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_624.geometry} material={materials.BookCover7} position={[3.356, 4.066, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_640.geometry} material={materials.BookCover7} position={[8.886, 6.057, 0.348]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_200.geometry} material={materials.BookCover7} position={[0.579, 4.041, -0.01]} rotation={[-Math.PI / 2, 0, 1.45]} scale={0.845} />
          <mesh geometry={nodes.Object_594.geometry} material={materials.BookPaper} position={[-0.028, 2.019, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_610.geometry} material={materials.BookPaper} position={[2.989, 4.066, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_626.geometry} material={materials.BookPaper} position={[3.445, 4.066, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_642.geometry} material={materials.BookPaper} position={[8.975, 6.057, 0.419]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_202.geometry} material={materials.BookPaper} position={[0.668, 4.041, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_596.geometry} material={materials.BookCover8} position={[-0.028, 2.019, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_612.geometry} material={materials.BookCover8} position={[2.989, 4.066, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_628.geometry} material={materials.BookCover8} position={[3.445, 4.066, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_644.geometry} material={materials.BookCover8} position={[8.975, 6.057, 0.419]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.BookCover8} position={[0.668, 4.041, 0.061]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_598.geometry} material={materials.BookPaper} position={[0.189, 2.019, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_614.geometry} material={materials.BookPaper} position={[3.207, 4.066, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_630.geometry} material={materials.BookPaper} position={[3.663, 4.066, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_646.geometry} material={materials.BookPaper} position={[9.193, 6.057, 0.456]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_206.geometry} material={materials.BookPaper} position={[0.886, 4.041, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_600.geometry} material={materials.BookCover9} position={[0.189, 2.019, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_616.geometry} material={materials.BookCover9} position={[3.207, 4.066, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_632.geometry} material={materials.BookCover9} position={[3.663, 4.066, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_648.geometry} material={materials.BookCover9} position={[9.193, 6.057, 0.456]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_208.geometry} material={materials.BookCover9} position={[0.886, 4.041, 0.098]} rotation={[-Math.PI / 2, 0, -1.692]} scale={0.845} />
          <mesh geometry={nodes.Object_6001.geometry} material={materials['Material.083']} position={[0.635, 6.014, 0.001]} scale={[1.734, 0.066, 1]} />
          <mesh geometry={nodes.Object_8002.geometry} material={materials['Material.084']} position={[0.66, 3.998, 0.001]} scale={[1.734, 0.066, 1]} />
          <mesh geometry={nodes.Object_10001.geometry} material={materials['Material.085']} position={[0.632, 1.979, 0.001]} scale={[1.734, 0.066, 1]} />
          <mesh geometry={nodes.Object_12001.geometry} material={materials['Material.086']} position={[5.819, 4.878, 0.001]} rotation={[0, 0, -1.568]} scale={[1, 0.115, 1]} />
          <mesh geometry={nodes.Object_14001.geometry} material={materials['Material.087']} position={[1.998, 4.879, 0.003]} rotation={[0, 0, -1.568]} scale={[1, 0.115, 1]} />
          <mesh geometry={nodes.Object_4001.geometry} material={materials['Material.082']} position={[-1.104, 0.88, 0]} scale={[0.103, 1, 1]} />
        </group>
      </group>
      <group position={[2.487, 1.392, 3.781]} rotation={[-Math.PI / 2, 0, 0]} scale={0.049}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.mat_pas117_fixture_doll2large_base} position={[-0.004, 0.908, -9.454]} rotation={[0, 0, -Math.PI / 2]} />
      </group>
      <group position={[-3.459, 0.249, 1.244]} rotation={[-Math.PI / 2, 0, 2.795]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-51.389, 55.287, -133.687]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Box02_Chairback_0.geometry} material={materials.Chairback} />
            <mesh geometry={nodes.Box02_Lether_0.geometry} material={materials.Lether} />
          </group>
          <group position={[-21.91, 2.302, -108.052]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cylinder01_BlackMetal_0.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Cylinder01_Matteplastic_0.geometry} material={materials.Matteplastic} />
          </group>
          <group position={[-21.91, -0.065, -108.052]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9.737, 28.277, -4.174]}>
              <mesh geometry={nodes.Cylinder04_Matteplastic_0.geometry} material={materials.Matteplastic} />
              <mesh geometry={nodes.Cylinder02_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-1.576, 0.248, -4.729]} />
            </group>
            <group position={[23.84, 17.931, -4.174]}>
              <mesh geometry={nodes.Cylinder20_Matteplastic_0.geometry} material={materials.Matteplastic} />
              <mesh geometry={nodes.Cylinder19_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-0.419, 1.539, -4.729]} />
            </group>
            <group position={[24.416, -17.128, -4.174]}>
              <mesh geometry={nodes.Cylinder21_Matteplastic_0.geometry} material={materials.Matteplastic} />
              <mesh geometry={nodes.Cylinder22_Matteplastic_0.geometry} material={materials.Matteplastic} position={[0.917, 1.305, -4.729]} />
            </group>
            <group position={[-8.754, -28.449, -4.174]}>
              <mesh geometry={nodes.Cylinder23_Matteplastic_0.geometry} material={materials.Matteplastic} />
              <mesh geometry={nodes.Cylinder24_Matteplastic_0.geometry} material={materials.Matteplastic} position={[1.58, -0.216, -4.729]} />
            </group>
            <group position={[-29.848, -0.519, -4.174]}>
              <mesh geometry={nodes.Cylinder26_Matteplastic_0.geometry} material={materials.Matteplastic} />
              <mesh geometry={nodes.Cylinder25_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-0.697, 1.434, -4.729]} />
            </group>
            <mesh geometry={nodes.Rectangle02_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <mesh geometry={nodes.Box01_Lether_0.geometry} material={materials.Lether} position={[7.49, 34.373, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Circle01_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-29.262, 24.564, -81.484]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder03_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-14.457, 23.805, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder07_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.739, 27.145, -126.39]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder08_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.851, 27.386, -126.404]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder09_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.9, 28.287, -131.49]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder10_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.787, 28.046, -131.476]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder11_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.777, 27.845, -84.724]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder12_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-18.728, 26.944, -89.81]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder13_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.889, 28.086, -84.71]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder14_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.84, 27.185, -89.796]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder15_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-19.862, 33.508, -79.262]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder16_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.681, 33.814, -79.195]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder17_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-12.681, 33.814, -136.428]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder18_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-19.862, 33.508, -136.361]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Line01_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-25.15, 24.272, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Line02_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-25.595, 24.171, -86.278]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Line04_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-18.111, 48.52, -79.051]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Line05_Matteplastic_0.geometry} material={materials.Matteplastic} position={[-18.111, 48.52, -136.572]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Rectangle11_BlackMetal_0.geometry} material={materials.BlackMetal} position={[-16.035, 30.479, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[-2.439, 0, 4.222]} rotation={[-Math.PI / 2, 0, 0]} scale={0.344}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[13.883, 108.539, 6.594]}>
            <mesh geometry={nodes.Cloner_Material3617_0.geometry} material={materials.Material3617} />
            <mesh geometry={nodes.Cloner_Material3617_0001.geometry} material={materials.Material3617} />
          </group>
          <mesh geometry={nodes.Pattern2D_5687_Material3737_0.geometry} material={materials.Material3737} position={[0, 0.337, 0]} />
        </group>
      </group>
      <group position={[-1.665, -0.151, 2.254]} rotation={[-Math.PI / 2, 0, 3.14]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.base_low_test_0.geometry} material={materials.test} position={[97.213, 115.705, -200.769]} rotation={[0, 1.571, 0]} scale={0.452} />
          <mesh geometry={nodes.igla_low_test_0.geometry} material={materials.test} position={[72.298, 141.308, -233.128]} rotation={[-Math.PI / 2, 0, -0.581]} scale={3.311} />
          <mesh geometry={nodes.klyapki_low_test_0.geometry} material={materials.test} position={[97.213, 115.705, -200.769]} rotation={[0, 1.571, 0]} scale={0.452} />
          <mesh geometry={nodes.nojki_low_test_0.geometry} material={materials.test} position={[73.489, 101.736, -200.655]} rotation={[-Math.PI / 2, 0, 0]} scale={[25.358, 32.978, 24.783]} />
          <mesh geometry={nodes.plastina_low_test_0.geometry} material={materials.test} position={[73.319, 112.916, -207.498]} rotation={[-Math.PI / 2, 0, 0]} scale={[25.358, 32.978, 14.509]} />
          <mesh geometry={nodes.rukoyatka_low_test_0.geometry} material={materials.test} position={[107.833, 106.609, -201.467]} rotation={[0.047, -1.571, 0]} scale={0.544} />
          <mesh geometry={nodes.truba_low_test_0.geometry} material={materials.test} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.093']} position={[-4.124, 1.922, 3.885]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.551} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.094']} position={[-4.989, 2.141, 2.979]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.454, 0.454, 0.645]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.096']} position={[-5.052, 2.163, 1.725]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.429} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.097']} position={[-5.033, 2.166, 0.482]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.452, 0.452, 0.651]} />
    </group>
  )
}

useGLTF.preload('/models/BaharRoom.glb')
