/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/modernGallery.glb \ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/BaharRoom.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tree.geometry} material={materials.Material} position={[-66, 16.666, 0]} rotation={[-Math.PI, 0.295, -Math.PI]} scale={1.3} />
      <group position={[-66, 15.366, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Base} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.Cushion} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Glass.001']} />
      </group>
      <group position={[0, 60.515, -71.197]} scale={[15, 32.471, 0.75]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Art Frame']} />
        <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
      </group>
      <group position={[65.506, 60.515, -71.197]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Frame} />
        <mesh geometry={nodes.Cube004_2.geometry} material={nodes.Cube004_2.material} />
      </group>
      <group position={[66, 15.366, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Base} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Cushion} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Glass.001']} />
      </group>
      <group position={[0, 15.366, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials.Base} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.Cushion} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Glass.001']} />
      </group>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.004']} position={[0, 23.562, 0]} scale={[4.321, 6.828, 4.321]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.005']} position={[65.844, 22.947, 0]} rotation={[-0.669, 0.365, 1.027]} scale={3.774} />
      <mesh geometry={nodes.Tree001.geometry} material={materials['Material.002']} position={[-66, 16.666, 0]} rotation={[-Math.PI, 0.295, -Math.PI]} scale={1.3} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.003']} position={[0, 23.562, 0]} scale={[4.321, 6.828, 4.321]} />
      <group position={[-65.506, 60.515, -71.197]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Frame.001']} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.006']} position={[65.844, 22.947, 0]} rotation={[-0.669, 0.365, 1.027]} scale={3.774} />
      <mesh geometry={nodes.Tree002.geometry} material={materials['Material.008']} position={[-55.048, 16.666, 122.131]} rotation={[Math.PI, -1.276, Math.PI]} scale={1.3} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.009']} position={[-55.048, 23.562, 56.131]} rotation={[0, Math.PI / 2, 0]} scale={[4.321, 6.828, 4.321]} />
      <group position={[-126.246, 60.515, 56.131]} rotation={[0, Math.PI / 2, 0]} scale={[15, 32.471, 0.75]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials['Art Frame.002']} />
        <mesh geometry={nodes.Cube017_1.geometry} material={nodes.Cube017_1.material} />
      </group>
      <group position={[-126.246, 60.515, 121.637]} rotation={[0, Math.PI / 2, 0]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['Frame.002']} />
      </group>
      <group position={[-126.246, 60.515, -9.375]} rotation={[0, Math.PI / 2, 0]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Frame.002']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={nodes.Cube019_1.material} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.010']} position={[-50.887, 22.947, -9.713]} rotation={[-2.123, 0.822, 3.021]} scale={3.774} />
      <group position={[-55.048, 15.366, 122.131]} rotation={[0, Math.PI / 2, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube021.geometry} material={materials['Base.002']} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials['Cushion.002']} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials['Glass.005']} />
      </group>
      <group position={[-50.887, 15.366, -9.869]} rotation={[0, Math.PI / 2, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube022.geometry} material={materials['Base.002']} />
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['Cushion.002']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials['Glass.005']} />
      </group>
      <group position={[-55.048, 15.366, 56.131]} rotation={[0, Math.PI / 2, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials['Base.002']} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['Cushion.002']} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials['Glass.005']} />
      </group>
      <mesh geometry={nodes.Tree003.geometry} material={materials['Material.012']} position={[66.492, 16.666, 111.77]} rotation={[0, -0.295, 0]} scale={1.3} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.013']} position={[0.492, 23.562, 111.77]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.321, 6.828, 4.321]} />
      <group position={[-65.014, 60.515, 182.967]} rotation={[-Math.PI, 0, -Math.PI]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube025.geometry} material={materials['Frame.003']} />
        <mesh geometry={nodes.Cube025_1.geometry} material={nodes.Cube025_1.material} />
      </group>
      <group position={[65.998, 60.515, 182.967]} rotation={[-Math.PI, 0, -Math.PI]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['Frame.003']} />
      </group>
      <group position={[0.492, 60.515, 182.967]} rotation={[-Math.PI, 0, -Math.PI]} scale={[15, 32.471, 0.75]}>
        <mesh geometry={nodes.Cube027.geometry} material={materials['Art Frame.003']} />
        <mesh geometry={nodes.Cube027_1.geometry} material={nodes.Cube027_1.material} />
      </group>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.014']} position={[-65.351, 22.947, 111.77]} rotation={[-2.472, -0.365, -2.115]} scale={3.774} />
      <group position={[0.492, 15.366, 111.77]} rotation={[-Math.PI, 0, -Math.PI]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials['Base.003']} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['Cushion.003']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Glass.007']} />
      </group>
      <group position={[-65.508, 15.366, 111.77]} rotation={[-Math.PI, 0, -Math.PI]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['Base.003']} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['Cushion.003']} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['Glass.007']} />
      </group>
      <group position={[66.492, 15.366, 111.77]} rotation={[-Math.PI, 0, -Math.PI]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Base.003']} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['Cushion.003']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['Glass.007']} />
      </group>
      <mesh geometry={nodes.Tree004.geometry} material={materials['Material.016']} position={[50.789, 16.666, -10.361]} rotation={[0, 1.276, 0]} scale={1.3} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.017']} position={[54.951, 23.562, 55.639]} rotation={[0, -1.571, 0]} scale={[4.321, 6.828, 4.321]} />
      <group position={[126.148, 60.515, 55.639]} rotation={[0, -1.571, 0]} scale={[15, 32.471, 0.75]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials['Art Frame.004']} />
        <mesh geometry={nodes.Cube033_1.geometry} material={nodes.Cube033_1.material} />
      </group>
      <group position={[126.148, 60.515, -9.867]} rotation={[0, -1.571, 0]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube034.geometry} material={nodes.Cube034.material} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials['Frame.004']} />
      </group>
      <group position={[126.148, 60.515, 121.145]} rotation={[0, -1.571, 0]} scale={[36, 22.73, 0.75]}>
        <mesh geometry={nodes.Cube035.geometry} material={materials['Frame.004']} />
        <mesh geometry={nodes.Cube035_1.geometry} material={nodes.Cube035_1.material} />
      </group>
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.018']} position={[54.951, 22.947, 121.482]} rotation={[-1.019, -0.822, -0.12]} scale={3.774} />
      <group position={[50.789, 15.366, -10.361]} rotation={[0, -1.571, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube037.geometry} material={materials['Base.004']} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['Cushion.004']} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['Glass.009']} />
      </group>
      <group position={[54.951, 15.366, 121.639]} rotation={[0, -1.571, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube038.geometry} material={materials['Base.004']} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['Cushion.004']} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials['Glass.009']} />
      </group>
      <group position={[54.951, 15.366, 55.639]} rotation={[0, -1.571, 0]} scale={[6.5, 1.3, 6.5]}>
        <mesh geometry={nodes.Cube039.geometry} material={materials['Base.004']} />
        <mesh geometry={nodes.Cube039_1.geometry} material={materials['Cushion.004']} />
        <mesh geometry={nodes.Cube039_2.geometry} material={materials['Glass.009']} />
      </group>
      <group position={[0.753, -0.634, 55.061]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[316.073, 316.073, 15.804]}>
        <mesh geometry={nodes.Cube040.geometry} material={materials['Art Frame.005']} />
        <mesh geometry={nodes.Cube040_1.geometry} material={nodes.Cube040_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/BaharRoom.glb')
