"use client";

import {
  useEffect,
  useMemo,
} from "react";

import * as THREE from "three";

import {
  useGLTF,
} from "@react-three/drei";

import {
  RigidBody,
} from "@react-three/rapier";

/*
 * THIS IS THE ACTUAL ROOM.
 *
 * BaharRoom.tsx was generated by gltfjsx.
 */
import {
  Model,
} from "./BaharRoom";

/* ======================================================
   TYPES
====================================================== */

type Vec3 = [
  number,
  number,
  number
];

export type RoomReadyData = {
  spawn: Vec3;

  lookAt: Vec3;

  offset: Vec3;

  bounds: {
    min: Vec3;
    max: Vec3;
  };
};

type RoomWorldProps = {
  onReady?: (
    data: RoomReadyData
  ) => void;

  onPointerDown?: (
    event: any
  ) => void;
};

/* ======================================================
   ROOM WORLD
====================================================== */

export default function RoomWorld({
  onReady,
  onPointerDown,
}: RoomWorldProps) {
  /*
   * We load the same GLB here so we can inspect:
   *
   * - room bounds
   * - PLAYER_SPAWN
   * - PLAYER_LOOK_AT
   *
   * The visible geometry itself is still rendered
   * through the gltfjsx-generated <Model />.
   */

  const {
    scene,
  } = useGLTF(
    "/models/BaharRoom.glb"
  );

  /* ====================================================
     CALCULATE ROOM POSITION
  ==================================================== */

  const roomData =
    useMemo(() => {
      scene.updateMatrixWorld(
        true
      );

      /* -----------------------------------------------
         COMPLETE ROOM BOUNDS
      ------------------------------------------------ */

      const bounds =
        new THREE.Box3()
          .setFromObject(
            scene
          );

      const center =
        bounds.getCenter(
          new THREE.Vector3()
        );

      /* -----------------------------------------------
         FIND BLENDER MARKERS
      ------------------------------------------------ */

      const spawnMarker =
        scene.getObjectByName(
          "PLAYER_SPAWN"
        );

      const lookAtMarker =
        scene.getObjectByName(
          "PLAYER_LOOK_AT"
        );

      /* -----------------------------------------------
         ORIGINAL SPAWN
      ------------------------------------------------ */

      const originalSpawn =
        new THREE.Vector3();

      if (
        spawnMarker
      ) {
        spawnMarker.getWorldPosition(
          originalSpawn
        );
      } else {
        /*
         * Fallback if you haven't exported
         * PLAYER_SPAWN yet.
         */

        originalSpawn.set(
          center.x,
          bounds.min.y,
          center.z
        );

        console.warn(
          "PLAYER_SPAWN not found in BaharRoom.glb"
        );
      }

      /* -----------------------------------------------
         WORLD OFFSET

         PLAYER_SPAWN becomes:

         X = 0
         Y = 0
         Z = 0

         Therefore the world/grid center is exactly
         the point in front of the bed that you chose
         in Blender.
      ------------------------------------------------ */

      const offset =
        new THREE.Vector3(
          -originalSpawn.x,
          -originalSpawn.y,
          -originalSpawn.z
        );

      /* -----------------------------------------------
         NORMALIZED SPAWN
      ------------------------------------------------ */

      const spawn =
        originalSpawn
          .clone()
          .add(
            offset
          );

      /* -----------------------------------------------
         INITIAL LOOK TARGET
      ------------------------------------------------ */

      const originalLookAt =
        new THREE.Vector3();

      if (
        lookAtMarker
      ) {
        lookAtMarker.getWorldPosition(
          originalLookAt
        );
      } else {
        /*
         * Fallback:
         * look toward room center.
         */

        originalLookAt.set(
          center.x,
          originalSpawn.y +
            1.4,
          center.z
        );

        console.warn(
          "PLAYER_LOOK_AT not found in BaharRoom.glb"
        );
      }

      const lookAt =
        originalLookAt
          .clone()
          .add(
            offset
          );

      /* -----------------------------------------------
         NORMALIZED ROOM BOUNDS
      ------------------------------------------------ */

      const normalizedMin =
        bounds.min
          .clone()
          .add(
            offset
          );

      const normalizedMax =
        bounds.max
          .clone()
          .add(
            offset
          );

      return {
        offset,

        spawn,

        lookAt,

        bounds: {
          min:
            normalizedMin,

          max:
            normalizedMax,
        },
      };
    }, [
      scene,
    ]);

  /* ====================================================
     INFORM SCENE ABOUT PLAYER START
  ==================================================== */

  useEffect(() => {
    onReady?.({
      spawn:
        roomData.spawn
          .toArray() as Vec3,

      lookAt:
        roomData.lookAt
          .toArray() as Vec3,

      offset:
        roomData.offset
          .toArray() as Vec3,

      bounds: {
        min:
          roomData.bounds.min
            .toArray() as Vec3,

        max:
          roomData.bounds.max
            .toArray() as Vec3,
      },
    });
  }, [
    onReady,
    roomData,
  ]);

  /* ====================================================
     ACTUAL ROOM

     THIS IS THE PART THAT RENDERS BAHARROOM.

     RigidBody:
       fixed = the room itself never moves

     trimesh:
       generates collision from the room geometry
  ==================================================== */

  return (
    <RigidBody
      type="fixed"

      colliders="trimesh"

      position={
        roomData.offset
          .toArray() as Vec3
      }

      friction={
        0.8
      }

      restitution={
        0
      }
    >
      <Model
        onPointerDown={
          onPointerDown
        }
      />
    </RigidBody>
  );
}

/* ======================================================
   PRELOAD GLB
====================================================== */

useGLTF.preload(
  "/models/BaharRoom.glb"
);